import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Button, Stack} from "@mui/material";
import PrimarySearchAppBar from "@/pages/common/layout/AppBar";

export default function Dashboard() {


    return (
        <>
            <Head>
                <title>Perfect time</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <PrimarySearchAppBar>
                    <Stack direction="column" spacing={2} width={"100%"} height={"70vh"} justifyContent={"center"}
                           alignItems={"center"}>
                        <div>
                            <h1>Welcome to Perfect Time</h1>

                        </div>
                    </Stack>
                </PrimarySearchAppBar>


            </main>
        </>
    )
}
